export const fetchMenuList = (): Promise<any> => {
  return new Promise((resolve) => {
    resolve({
      code: 0,
      message: null,
      data: [
        {
          id: 13228,
          navName: '全部应用',
          webUrl: '/application',
          visible: true,
          icon: '',
          privType: 1,
          children: [
            {
              id: 13243,
              navName: '查看全部应用',
              webUrl: 'APPLICATION_VIEW',
              visible: true,
              icon: '',
              privType: 0,
              children: [],
              name: '查看全部应用',
              path: 'APPLICATION_VIEW',
              hideInMenu: true,
            },
          ],
          name: '全部应用',
          path: '/application',
          hideInMenu: false,
        },
        {
          id: 13229,
          navName: '权限管理',
          webUrl: '/permission',
          visible: true,
          icon: '',
          privType: 1,
          children: [
            {
              id: 13230,
              navName: '权限配置',
              webUrl: '/permission/config',
              visible: true,
              icon: '',
              privType: 1,
              children: [
                {
                  id: 13231,
                  navName: '系统权限',
                  webUrl: '/permission/config/system',
                  visible: true,
                  icon: '',
                  privType: 1,
                  children: [
                    {
                      id: 13234,
                      navName: '查看系统权限列表',
                      webUrl: 'PERMISSION_CONFIG_SYSTEM_LIST',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '查看系统权限列表',
                      path: 'PERMISSION_CONFIG_SYSTEM_LIST',
                      hideInMenu: true,
                    },
                    {
                      id: 13237,
                      navName: '新增系统权限',
                      webUrl: 'PERMISSION_CONFIG_SYS_ADD',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '新增系统权限',
                      path: 'PERMISSION_CONFIG_SYS_ADD',
                      hideInMenu: true,
                    },
                    {
                      id: 13238,
                      navName: '删除系统权限',
                      webUrl: 'PERMISSION_CONFIG_SYS_DELETE',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '删除系统权限',
                      path: 'PERMISSION_CONFIG_SYS_DELETE',
                      hideInMenu: true,
                    },
                  ],
                  name: '系统权限',
                  path: '/permission/config/system',
                  hideInMenu: false,
                },
                {
                  id: 13232,
                  navName: '部门权限',
                  webUrl: '/permission/config/organization',
                  visible: true,
                  icon: '',
                  privType: 1,
                  children: [
                    {
                      id: 13235,
                      navName: '查看部门权限列表',
                      webUrl: 'PERMISSION_CONFIG_ORG_LIST',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '查看部门权限列表',
                      path: 'PERMISSION_CONFIG_ORG_LIST',
                      hideInMenu: true,
                    },
                    {
                      id: 13239,
                      navName: '新增部门权限',
                      webUrl: 'PERMISSION_CONFIG_ORG_ADD',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '新增部门权限',
                      path: 'PERMISSION_CONFIG_ORG_ADD',
                      hideInMenu: true,
                    },
                    {
                      id: 13240,
                      navName: '删除部门权限',
                      webUrl: 'PERMISSION_CONFIG_ORG_DELETE',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '删除部门权限',
                      path: 'PERMISSION_CONFIG_ORG_DELETE',
                      hideInMenu: true,
                    },
                  ],
                  name: '部门权限',
                  path: '/permission/config/organization',
                  hideInMenu: false,
                },
                {
                  id: 13233,
                  navName: '应用权限',
                  webUrl: '/permission/config/application',
                  visible: true,
                  icon: '',
                  privType: 1,
                  children: [
                    {
                      id: 13236,
                      navName: '查看应用权限列表',
                      webUrl: 'PERMISSION_CONFIG_APP_LIST',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '查看应用权限列表',
                      path: 'PERMISSION_CONFIG_APP_LIST',
                      hideInMenu: true,
                    },
                    {
                      id: 13241,
                      navName: '新增应用权限',
                      webUrl: 'PERMISSION_CONFIG_APP_ADD',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '新增应用权限',
                      path: 'PERMISSION_CONFIG_APP_ADD',
                      hideInMenu: true,
                    },
                    {
                      id: 13242,
                      navName: '删除应用权限',
                      webUrl: 'PERMISSION_CONFIG_APP_DELETE',
                      visible: true,
                      icon: '',
                      privType: 0,
                      children: [],
                      name: '删除应用权限',
                      path: 'PERMISSION_CONFIG_APP_DELETE',
                      hideInMenu: true,
                    },
                  ],
                  name: '应用权限',
                  path: '/permission/config/application',
                  hideInMenu: false,
                },
              ],
              name: '权限配置',
              path: '/permission/config',
              hideInMenu: false,
            },
          ],
          name: '权限管理',
          path: '/permission',
          hideInMenu: false,
        },
        // {
        //   id: 13421,
        //   navName: '灰度管理',
        //   webUrl: '/gray',
        //   visible: true,
        //   icon: '',
        //   privType: 1,
        //   children: [
        //     {
        //       id: 13422,
        //       navName: '应用管理',
        //       webUrl: '/gray/application',
        //       visible: true,
        //       icon: '',
        //       privType: 1,
        //       children: [],
        //       name: '应用管理',
        //       path: '/gray/application',
        //       hideInMenu: false,
        //     },
        //     {
        //       id: 13423,
        //       navName: '发布管理',
        //       webUrl: '/gray/publish',
        //       visible: true,
        //       icon: '',
        //       privType: 1,
        //       children: [
        //         {
        //           id: 13425,
        //           navName: '需求流水线',
        //           webUrl: '/gray/publish/demand',
        //           visible: true,
        //           icon: '',
        //           privType: 1,
        //           children: [],
        //           name: '需求流水线',
        //           path: '/gray/publish/demand',
        //           hideInMenu: false,
        //         },
        //         {
        //           id: 13426,
        //           navName: '服务流水线',
        //           webUrl: '/gray/publish/service',
        //           visible: true,
        //           icon: '',
        //           privType: 1,
        //           children: [],
        //           name: '服务流水线',
        //           path: '/gray/publish/service',
        //           hideInMenu: false,
        //         },
        //       ],
        //       name: '发布管理',
        //       path: '/gray/publish',
        //       hideInMenu: false,
        //     },
        //     {
        //       id: 13424,
        //       navName: '灰度设置',
        //       webUrl: '/gray/setting',
        //       visible: true,
        //       icon: '',
        //       privType: 1,
        //       children: [
        //         {
        //           id: 13427,
        //           navName: '全局设置',
        //           webUrl: '/gray/setting/global',
        //           visible: true,
        //           icon: '',
        //           privType: 1,
        //           children: [],
        //           name: '全局设置',
        //           path: '/gray/setting/global',
        //           hideInMenu: false,
        //         },
        //         {
        //           id: 13428,
        //           navName: '白名单设置',
        //           webUrl: '/gray/setting/whitelist',
        //           visible: true,
        //           icon: '',
        //           privType: 1,
        //           children: [],
        //           name: '白名单设置',
        //           path: '/gray/setting/whitelist',
        //           hideInMenu: false,
        //         },
        //       ],
        //       name: '灰度设置',
        //       path: '/gray/setting',
        //       hideInMenu: false,
        //     },
        //   ],
        //   name: '灰度管理',
        //   path: '/gray',
        //   hideInMenu: false,
        // },
      ],
    })
  })
}
